---
title: "SIR_Augmentation"
author: "Volodymyr Minin, Kari Auranen, Elizabeth Halloran"
date: '2023'
output:
  html_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  fig.path = "./figs/ex02-", results = "markup", error = FALSE, fig.width = 8,
  fig.height = 4.5, size = "small", echo = TRUE, tidy = FALSE, message = FALSE,
  fig.keep = "high", fig.align = "center", warning = FALSE
)
```

```{r include=FALSE}
options(width = 120)
# Libraries
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  tidyverse, gridExtra, pbapply, deSolve, RColorBrewer, rstan, data.frame, outbreaks
)
```

```{r}
original_data <- ebola_kikwit_1995 
```

```{r}
N <- 300

my_data <- data.frame(t = 0:132,
                      IN = original_data$onset[60:192],
                      RN = original_data$death[60:192],
                      S = rep(0,length(t)),
                      I = rep(0,length(t)),
                      R = rep(0,length(t)))
my_data$I[1] = 1
my_data$S[1] = N - 1
my_data$R[1] = 0
for (i in 2:133){
  my_data$I[i] = my_data$I[i-1] + my_data$IN[i] - my_data$RN[i]
}

for (i in 2:133){
  my_data$R[i] = my_data$R[i-1] + my_data$RN[i] 
}
my_data$S = N - my_data$I - my_data$R
```

```{r}
#pdf("4dataset2newcases.pdf")
plot(my_data$t, my_data$IN,
  lwd = 2, type = "l", lty = 1,
  ylab = "Number of new infections",
  xlab = "Time", col = 2
)
title("Observed data")

#dev.off()
```

```{r}
#pdf("4dataset2process.pdf")
plot(my_data$t, my_data$S,
  lwd = 2, type = "l", lty = 1,
  ylab = "Number of individuals",
  xlab = "Time", col = 1
)
lines(my_data$t, my_data$I, col = 2)
lines(my_data$t, my_data$R, col = 3)
legend(x = "topright", c("S(t)", "I(t)","R(t)"), col = c(1,2,3), lty = 1)
title("Observed data")
#dev.off()
```

```{r}
start = 0

#data we have, from day start to start+days-1 so days = n +1
days = 81

#Predicts 10 days after #91
days_pred = 10

#Number of interations
iterations = 1000

#Create a prediction table
sm_pred <- data.frame(iter = 1:iterations)

for (i in 1:(days+days_pred)){
  column_name <- paste("R", i, sep="")  # Dynamically create the column name
  sm_pred[[column_name]] <- NA
}

for (i in 2:days){
  sm_pred[,i] = rep(my_data$R[start+i], times = iterations)
}
```

```{r}
pred_sim <- function(N, beta, gamma, S_init, I_init, days_pred){
  result = c(NA)
  S = S_init
  I = I_init
  for (i in 1: (days_pred+1)){
    IN_new = rpois(1, lambda = S*I*beta/N)
    RN_new = rpois(1, lambda = I*gamma)
    S = S - IN_new
    I = I + IN_new - RN_new
    R = N - S - I
    result = c(result, R)
  }
  return(result[-1])
}
```

```{r}
# Posterior parameters
a_beta = 0.01
b_beta = 0.01

a_gamma = 0.01
b_gamma = 0.01

#We know the data for 5 days
#Update the parameters
a_beta = a_beta + sum(my_data$IN[(start + 2):(start + days)]) 
b_beta = b_beta + sum(my_data$S[(start + 1):(start + days-1)]*my_data$I[(start + 1):(start + days-1)]/N) 

a_gamma = a_gamma + sum(my_data$RN[(start + 2):(start + days)]) 
b_gamma = b_gamma + sum(my_data$I[(start + 1):(start + days-1)]) 

```


```{r}
for (i in 1:iterations){
  beta = rgamma(1, shape = a_beta, rate = b_beta)
  gamma = rgamma(1, shape = a_gamma, rate = b_gamma)
  I_init = my_data$I[start+days]
  S_init = my_data$S[start+days]
  new_row = pred_sim(N, beta, gamma, S_init, I_init, days_pred)
  sm_pred[i,(days+1):(days+days_pred+1)] = new_row
}

```

```{r}
summary <- data.frame(t = 1:(days+days_pred),
                      cases = numeric(length(t)),
                      R_pred = numeric(length(t)),
                      X5 = numeric(length(t)),
                      X50 = numeric(length(t)),
                      X95 = numeric(length(t)))

for (i in 1:length(summary$t)){
  summary$cases[i] = my_data$R[start+i+1]
  summary$R_pred[i] = round(mean(sm_pred[,(i+1)], na.rm = TRUE),0)
  summary$X5[i] = quantile(sm_pred[,i+1],0.05, na.rm = TRUE)
  summary$X50[i] = quantile(sm_pred[,i+1],0.50, na.rm = TRUE)
  summary$X95[i] = quantile(sm_pred[,i+1],0.95, na.rm = TRUE)
} 
```

```{r}
pdf("4dataset2_80days_finalsize.pdf")
#plot the histogram
ggplot(summary, mapping = aes(x = t)) + 
  geom_ribbon(aes(ymin = X5, ymax = X95), fill = "blue", alpha = 0.6) + 
  geom_line(mapping = aes(x = t, y = R_pred)) + 
  geom_point(mapping = aes(y = cases)) + 
  labs(x = "Days", y = "Number of new removal individuals")
dev.off()
```
